[repository]
name = "hyprwinview"
authors = ["Ivan Malison", "Raymond Bian"]
commit_pins = [
    # Hyprland v0.56.0                          hyprwinview v0.1.0
    ["36b2e0cfe0c6094dbc47bd42a437431315bb3087", "30796826ad253b886682d70b01564509cb721d66"],
]

[hyprwinview]
description = "Window and workspace overviews for Hyprland"
authors = ["Ivan Malison", "Raymond Bian"]
output = "build/libhyprwinview.so"
build = [
    "cmake -S . -B build -DCMAKE_BUILD_TYPE=Release",
    "cmake --build build --target hyprwinview",
]
